/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.MyMath.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Alumno
 */
public class MenuOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public MenuOperaciones() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuOpcionesFactorial = new javax.swing.JMenuItem();
        menuOpcionesMCD = new javax.swing.JMenuItem();
        menuOpcionesFibonacci = new javax.swing.JMenuItem();
        menuOpcionesPrimos = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Operaciones");

        menuOpcionesFactorial.setText("Factorial");
        menuOpcionesFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesFactorialActionPerformed(evt);
            }
        });
        fileMenu.add(menuOpcionesFactorial);

        menuOpcionesMCD.setText("MCD y MCM");
        menuOpcionesMCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesMCDActionPerformed(evt);
            }
        });
        fileMenu.add(menuOpcionesMCD);

        menuOpcionesFibonacci.setText("Fibonacci");
        menuOpcionesFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesFibonacciActionPerformed(evt);
            }
        });
        fileMenu.add(menuOpcionesFibonacci);

        menuOpcionesPrimos.setText("Primos");
        menuOpcionesPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesPrimosActionPerformed(evt);
            }
        });
        fileMenu.add(menuOpcionesPrimos);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuOpcionesFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesFactorialActionPerformed
        cargarFormulario(formFactorial.class);
    }//GEN-LAST:event_menuOpcionesFactorialActionPerformed

    private void menuOpcionesPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesPrimosActionPerformed
        cargarFormulario(formPrimos.class);
    }//GEN-LAST:event_menuOpcionesPrimosActionPerformed

    private void menuOpcionesMCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesMCDActionPerformed
        cargarFormulario(formMCD_MCM.class);
    }//GEN-LAST:event_menuOpcionesMCDActionPerformed

    private void menuOpcionesFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesFibonacciActionPerformed
        cargarFormulario(formFibonacci.class);
    }//GEN-LAST:event_menuOpcionesFibonacciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOperaciones().setVisible(true);
            }
        });
    }
    
    private void cargarFormulario (Class<?> aClass){
        try {
           JInternalFrame view = null;
           
           //Buscar Objeto
           for(JInternalFrame form: desktopPane.getAllFrames()){
               if(aClass.isInstance(form)){
                   view=form;
                   break;
               }
           }
           //Si No lo Encuentra
           if (view == null){
               view=(JInternalFrame)Class.forName(aClass.getName()).newInstance();
               desktopPane.add(view);
           }
           //Hacer Visible el formulario
           view.setVisible(true);
           view.setSelected(true);
           
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuOpcionesFactorial;
    private javax.swing.JMenuItem menuOpcionesFibonacci;
    private javax.swing.JMenuItem menuOpcionesMCD;
    private javax.swing.JMenuItem menuOpcionesPrimos;
    // End of variables declaration//GEN-END:variables

}
